<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        tr:nth-child(even) {
            background: #232323
        }

        tr:nth-child(odd) {
            background: #2e2e2e
        }

        table, tr, td {
            border: none;
        }

        td, th {
            padding: 0;
            display: table-cell;
            vertical-align: inherit;
        }

        table {
            background-color: transparent;
            display: table;
            border-collapse: collapse;
            border-color: grey;
            border-spacing: 0;
            width: 100%;
            max-width: 100%;
            margin-bottom: 20px;
        }

        html, body, p {
            font-family: Verdana, Arial, Helvetica, sans-serif;
            margin: 0;
            padding: 0;
        }

        html {
            -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
            font-family: sans-serif;
            -webkit-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
        }

        body {
            line-height: 1.42857143;
            background-color: #2e2e2e;
            color: white;
        }

        .menuItem {
            cursor: pointer;
            padding: 1.75em 1em;
        }

        .chevron{
            height: 2em;
            width: 2em;
            background: url("data:image/svg+xml;utf8,<svg version='1.1' id='icon' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' width='24px' height='24px' viewBox='7 7 10 17' enable-background='new 0 16 24 17' xml:space='preserve'><polygon id='chevron' fill='#FFFFFF' points='16,12 11,7 9,9 12,12 9,15 11,17 '/></svg>") no-repeat center left;
        }
    </style>
</head>
<body>
<table>
    <?php foreach ($this->toUrls as $countryName => $toUrl): ?>
        <tr>
            <td>
                <form onclick="this.submit()" method="post">
                    <input type="hidden" name="countryName" value="<?= $countryName ?>">

                    <div class="menuItem">
                        <?= $countryName ?>
                        <span class="chevron" aria-hidden="true"
                              style="float:right"></span>
                    </div>
                </form>
            </td>
        </tr>
    <?php endforeach ?>
</table>

</body>
</html>
